# -*- coding: utf-8 -*-
"""Calculate The Tip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivV42itXfzWm8SrVesNSwSBsItw7kJJY

# TIP CALCULATION SYSTEM

## 18% TIP
"""

# 18% tip

def eightteen_percent(total_bill):
  eighteen_percent_tip = (18 * total_bill)/100
  return eighteen_percent_tip

"""## 20% TIP"""

# 20% tip
def twenty_percent(total_bill):
  twenty_percent_tip = (20 * total_bill)/100
  return twenty_percent_tip

"""## 25% TIP

"""

# 25% tip
def twenrt_five_percent(total_bill):
  twenrt_five_percent_tip = (25 * total_bill)/100
  return twenrt_five_percent_tip

"""## Taking Input"""

def take_input():
  import sys
  total_bill = float(input("What's the total bull for today, Please? $ "))
  number_of_person = int(input("Please Enter Number of Persons: "))
  contribute_list = []
  for i in range(number_of_person):
    print("Person {} will contribute in (percentage): ".format(i+1),end="")
    contribute_list.append(float(input()))

  if(sum(contribute_list) == 100.0):

    return total_bill, number_of_person, contribute_list
  else:
    print("\n\n --> NOTE: The sum of the contribution is not 100%. Please try again\n\n")
    sys.exit()

"""## Welcome"""

def welcome():
  print(" \n\n*** WELCOME TO THE TIP CALCULATION SYSTEM ****\n\n")

"""## Distributing the total bill (Inclulding the tip)"""

def distribute_bill(total_bill, number_of_person, eighteen_percent_tip, twenty_percent_tip, twenrt_five_percent_tip):
  
  print("\n ## FOR 18% TIP: ")

  for i in range(number_of_person):
    print("Person {} will contribute (in $): ".format(i+1),end="")
    print((contribute_list[i] * (eighteen_percent_tip + total_bill))/100)

  print("\n ## FOR 20% TIP: ")

  for i in range(number_of_person):
    print("Person {} will contribute (in $): ".format(i+1),end="")
    print((contribute_list[i] * (twenty_percent_tip + total_bill))/100)

  print("\n ## FOR 25% TIP: ")

  for i in range(number_of_person):
    print("Person {} will contribute (in $): ".format(i+1),end="")
    print((contribute_list[i] * (twenrt_five_percent_tip + total_bill))/100)

"""## Main Function"""

if __name__ == "__main__":

  welcome()
  total_bill, number_of_person, contribute_list = take_input()
  eighteen_percent_tip = eightteen_percent(total_bill)
  twenty_percent_tip = twenty_percent(total_bill)
  twenrt_five_percent_tip = twenrt_five_percent(total_bill)

  print("\n18% tip is ${}, which brings your total to ${} ≈ ${} [After Round Up]".format(eighteen_percent_tip, (eighteen_percent_tip + total_bill), round(eighteen_percent_tip + total_bill)))
  print("20% tip is ${}, which brings your total to ${} ≈ ${} [After Round Up]".format(twenty_percent_tip, (twenty_percent_tip + total_bill), round(twenty_percent_tip + total_bill)))
  print("25% tip is ${}, which brings your total to ${} ≈ ${} [After Round Up]".format(twenrt_five_percent_tip, (twenrt_five_percent_tip + total_bill), round(twenrt_five_percent_tip + total_bill)))

  distribute_bill(total_bill, number_of_person, eighteen_percent_tip, twenty_percent_tip, twenrt_five_percent_tip)